apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80
    # targetport: 80 caso eu queira especificar uma porta de saida
      nodePort: 30000
  selector:
    app: portal-noticias